export const GET_BLOG_EPIC = 'GET_BLOG_EPIC';
export const GET_BLOG_LOADING = 'GET_BLOG_LOADING';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_ERROR = 'GET_BLOG_ERROR';
export const GET_BLOG_CANCEL = 'GET_BLOG_CANCEL';

export const POST_BLOG_EPIC = 'POST_BLOG_EPIC';
export const POST_BLOG_LOADING = 'POST_BLOG_LOADING';
export const POST_BLOG_SUCCESS = 'POST_BLOG_SUCCESS';
export const POST_BLOG_ERROR = 'POST_BLOG_ERROR';
export const POST_BLOG_CANCEL = 'POST_BLOG_CANCEL';

export const PATCH_BLOG_EPIC = 'PATCH_BLOG_EPIC';
export const PATCH_BLOG_LOADING = 'PATCH_BLOG_LOADING';
export const PATCH_BLOG_SUCCESS = 'PATCH_BLOG_SUCCESS';
export const PATCH_BLOG_ERROR = 'PATCH_BLOG_ERROR';
export const PATCH_BLOG_CANCEL = 'PATCH_BLOG_CANCEL';

export const PUT_BLOG_EPIC = 'PUT_BLOG_EPIC';
export const PUT_BLOG_LOADING = 'PUT_BLOG_LOADING';
export const PUT_BLOG_SUCCESS = 'PUT_BLOG_SUCCESS';
export const PUT_BLOG_ERROR = 'PUT_BLOG_ERROR';
export const PUT_BLOG_CANCEL = 'PUT_BLOG_CANCEL';

export const DELETE_BLOG_EPIC = 'DELETE_BLOG_EPIC';
export const DELETE_BLOG_LOADING = 'DELETE_BLOG_LOADING';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_ERROR = 'DELETE_BLOG_ERROR';
export const DELETE_BLOG_CANCEL = 'DELETE_BLOG_CANCEL';
